name: help_desktops
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  retrofit: ^4.9.2
  retrofit_generator: ^10.2.1
  pretty_dio_logger: ^1.4.0
  flutter_native_splash: ^2.4.7
  flutter_bloc: ^9.1.1
  build_runner: ^2.10.4
  freezed: ^3.2.4
  freezed_annotation: ^3.1.0
  get_it: ^9.2.0
  json_serializable: ^6.11.3
  json_annotation: ^4.9.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
